#!/bin/bash

# Print help message if -h flag is used
if [ "$1" == "-h" ]; then
  echo "Usage: ./script.sh [domain]"
  echo "Runs subfinder, crtsh, githubsubs, assetfinder, amass, and asnmap on the specified domain"
  exit 0
fi

# Prompt the user for the domain if not provided
if [ -z "$1" ]; then
  read -p "Enter the domain to run the process on: " DOMAIN
else
  DOMAIN=$1
fi

# Create the subdomains folder if it does not exist
if [ ! -d "subdomains" ]; then
  mkdir subdomains
fi

# Run the tools with their flags
subfinder -d $DOMAIN -o subdomains/subfinder-subs
crtsh -d $DOMAIN -r > subdomains/crtsh-subs
githubsubs -d $DOMAIN -e -t "GITHUB TOKEN" > subdomains/githubsubs
assetfinder $DOMAIN > subdomains/assetfinder-subs
amass enum -d $DOMAIN -ip -alts -active -o subdomains/amass-output
asnmap -d $DOMAIN -o subdomains/asn-IPs

  # Extract IP addresses and save to DOMAIN-IPs file
  cat /home/dynamo/bugbounty/indeed/subdomains/amass-output | awk -F " " '{print $2}' |sed 's/,/\n/g' > subdomains/amass-IPs  
  # Extract domains and save to DOMAIN-subs-extracted file
  cat /home/dynamo/bugbounty/indeed/subdomains/amass-subs | awk -F " " '{print $1}' > subdomains/amass-subs
   
 #Parse all found subdomains, combine them into one file "all-subs" ready next phase.
 cat subfinder-subs crtsh-subs githubsubs assetfinder-subs amass-subs | uniq > subdomains/all-subs
 #Parse all foud IPs, combine them into one file "all-IPs" ready for next phase.
 cat amass-IPs asn-IPs | uniq > subdomains/all-IPs

#TODO: BUILD on this, make it 1Click recon like other frameworks
